-- MB-7: the Release 1.0 ledger schema.
-- Specified by SRS 1.10 sections 4.1-4.2, Technical Design sections 3-4, ADR-015 and
-- MB-7's acceptance criteria. Never edit this file once merged: a change is a new
-- migration (ADR-015).
--
-- Conventions used throughout:
--   * Primary keys are UUIDs generated by the application (ADR-015). No DEFAULT
--     gen_random_uuid(): the application always supplies the key, so an insert that
--     forgets it fails loudly instead of silently inventing one.
--   * Enumerations are text columns with a CHECK, not Postgres enum types. The allowed
--     values are still enforced by the database, but plain JDBC can bind them as
--     strings without casts, and Release 2.0 can extend a list (forgiveness) by
--     replacing one named constraint.
--   * Every constraint is named, so a violation reports which rule it broke and the
--     tests can assert on that name.
--   * Timestamps are timestamptz, stored in UTC. transaction_date is a DATE (ADR-012).
--   * Money is integer minor units of the row's own currency (CON-5, INT-1, ADR-013).
--     Never numeric, decimal or floating point. Deliberately integer, not bigint:
--     Postgres returns bigint for SUM(integer) but numeric for SUM(bigint), so with
--     integer amounts the balance views stay integral with no casts. The ceiling of
--     2,147,483,647 minor units per row ($21 million; 2.1 billion XAF) is far above
--     any family loan, and an insert beyond it fails rather than wrapping.

-- ---------------------------------------------------------------------------------
-- member: a provisioned family account (SRS 4.2).
-- No credential column of any kind (CON-9, T-Sec-4a) and no balance column (INT-2,
-- ADR-002): every balance is derived from approved transactions by the views below.
-- ---------------------------------------------------------------------------------
CREATE TABLE member (
    member_id     uuid        NOT NULL,
    idp_subject   text        NOT NULL,   -- the only authentication data stored (CON-9)
    email         text        NOT NULL,
    display_name  text        NOT NULL,
    time_zone     text        NOT NULL,   -- IANA name, e.g. Africa/Douala; validated by the application (CON-8, ADR-012)
    role          text        NOT NULL,
    status        text        NOT NULL DEFAULT 'active',
    created_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT member_pk              PRIMARY KEY (member_id),
    CONSTRAINT member_idp_subject_key UNIQUE (idp_subject),
    CONSTRAINT member_email_key       UNIQUE (email),
    -- Emails are stored lower-cased, so the unique key and the allow-list match cannot
    -- be sidestepped by capitalisation (Auth.Roles-9).
    CONSTRAINT member_email_lower     CHECK (email = lower(email)),
    CONSTRAINT member_role_check      CHECK (role IN ('family_member', 'family_administrator')),
    CONSTRAINT member_status_check    CHECK (status IN ('active', 'deactivated'))
);

-- ---------------------------------------------------------------------------------
-- allowed_email: the access allow-list. Presence is the sole gate on access
-- (Auth.Roles-9).
--
-- Deliberately unlinked from member: there is no foreign key between member.email and
-- this table in either direction, so deleting a row here can never cascade to a member
-- or a transaction (Data-7). It only stops future sign-in.
--
-- added_by is nullable because the first administrator's address has to be on the list
-- before any member exists to have added it. That bootstrap row is the only one
-- expected to have no author.
-- ---------------------------------------------------------------------------------
CREATE TABLE allowed_email (
    email     text        NOT NULL,
    added_by  uuid,
    added_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT allowed_email_pk       PRIMARY KEY (email),
    CONSTRAINT allowed_email_lower    CHECK (email = lower(email)),
    CONSTRAINT allowed_email_added_by_fk FOREIGN KEY (added_by) REFERENCES member (member_id)
);

-- ---------------------------------------------------------------------------------
-- transaction: one recorded exchange, in one currency (SRS 4.2).
--
-- Direction convention (SRS 4.2 as clarified in 1.10, CR-14; Technical Design D2):
-- creditor_id and debtor_id give the direction of THIS row's own effect. The creditor
-- gains a claim of amount_minor on the debtor.
--   loan          lender   -> borrower
--   repayment     borrower -> lender
--   compensating  the corrected row's parties, swapped
-- So every balance is one sum over approved rows, with no per-kind signs.
--
-- Append-only (ADR-003, Data-2, Data-6, Data-8): the application never deletes a row in
-- any state and never updates an approved one. A status change from pending is the only
-- update it makes.
-- ---------------------------------------------------------------------------------
CREATE TABLE transaction (
    transaction_id          uuid        NOT NULL,
    kind                    text        NOT NULL,
    creditor_id             uuid        NOT NULL,
    debtor_id               uuid        NOT NULL,
    amount_minor            integer     NOT NULL,
    currency                char(3)     NOT NULL,
    transaction_date        date        NOT NULL,
    note                    text,
    status                  text        NOT NULL DEFAULT 'pending',
    decline_reason          text,
    initiated_by            uuid        NOT NULL,
    created_at              timestamptz NOT NULL DEFAULT now(),
    decided_at              timestamptz,
    settles_transaction_id  uuid,
    corrects_transaction_id uuid,
    is_opening_balance      boolean     NOT NULL DEFAULT false,
    submission_key          uuid        NOT NULL,

    CONSTRAINT transaction_pk PRIMARY KEY (transaction_id),

    CONSTRAINT transaction_kind_check   CHECK (kind IN ('loan', 'repayment', 'compensating')),
    CONSTRAINT transaction_status_check CHECK (status IN ('pending', 'approved', 'declined', 'cancelled')),

    CONSTRAINT transaction_creditor_fk  FOREIGN KEY (creditor_id)  REFERENCES member (member_id),
    CONSTRAINT transaction_debtor_fk    FOREIGN KEY (debtor_id)    REFERENCES member (member_id),
    CONSTRAINT transaction_initiator_fk FOREIGN KEY (initiated_by) REFERENCES member (member_id),

    -- Ledger.Entry-2: strictly positive. Direction lives in creditor/debtor, never in a sign.
    CONSTRAINT transaction_amount_positive  CHECK (amount_minor > 0),
    -- Ledger.Entry-3: nobody lends to themselves.
    CONSTRAINT transaction_distinct_parties CHECK (creditor_id <> debtor_id),
    -- Ledger.Entry-13, ADR-013. ISO 4217 codes; never converted.
    CONSTRAINT transaction_currency_check   CHECK (currency IN ('USD', 'XAF', 'EUR')),
    -- Only a party creates a record. Release 2.0 relaxes this for the family
    -- administrator proposing a forgiveness (TBD-14).
    CONSTRAINT transaction_initiator_is_party CHECK (initiated_by IN (creditor_id, debtor_id)),
    -- INT-9: only a loan may be an opening balance.
    CONSTRAINT transaction_opening_balance_is_loan CHECK (NOT is_opening_balance OR kind = 'loan'),

    -- A repayment names the loan it settles and a compensating entry names the row it
    -- reverses (MB-7). Stated both ways round here: the reference is required on its own
    -- kind and forbidden on the others, so a loan can never carry a stray reference.
    CONSTRAINT transaction_repayment_settles
        CHECK ((kind = 'repayment') = (settles_transaction_id IS NOT NULL)),
    CONSTRAINT transaction_compensating_corrects
        CHECK ((kind = 'compensating') = (corrects_transaction_id IS NOT NULL)),

    -- SRS 4.2: decided_at is null exactly while pending; decline_reason only on declined.
    CONSTRAINT transaction_decided_at_check
        CHECK ((status = 'pending') = (decided_at IS NULL)),
    CONSTRAINT transaction_decline_reason_check
        CHECK (decline_reason IS NULL OR status = 'declined'),

    -- Target of the composite foreign keys below. transaction_id is already unique on
    -- its own; this pair exists so a reference can also pin the currency.
    CONSTRAINT transaction_id_currency_key UNIQUE (transaction_id, currency),

    -- INT-8: a repayment or correction is in the currency of the row it references.
    -- Because the foreign key covers (id, currency), a row pointing at a target in
    -- another currency simply has no parent row to match. When the reference is null
    -- (a loan), the key is not checked at all.
    CONSTRAINT transaction_settles_fk
        FOREIGN KEY (settles_transaction_id, currency)
        REFERENCES transaction (transaction_id, currency),
    CONSTRAINT transaction_corrects_fk
        FOREIGN KEY (corrects_transaction_id, currency)
        REFERENCES transaction (transaction_id, currency),

    -- Ledger.Entry-14, Technical Design D1: a retried POST carries the same key and hits
    -- this constraint; the service then returns the existing record as a success.
    CONSTRAINT transaction_submission_key UNIQUE (initiated_by, submission_key)
);

-- INT-6, Technical Design D3: at most one APPROVED compensating entry per target.
-- A partial index, because a plain UNIQUE would also count declined and cancelled
-- corrections, and one declined correction would block its target forever (T-Hist-11c).
CREATE UNIQUE INDEX transaction_one_approved_correction
    ON transaction (corrects_transaction_id)
    WHERE status = 'approved';

-- Deliberately NOT unique (INT-5 as changed in SRS 1.10, CR-14). A loan may carry any
-- number of repayments over its life: declined, cancelled, and approved-then-reversed
-- ones. "At most one approved repayment that has not been reversed" cannot be written
-- as an index, so it is enforced by locking the loan row while approving
-- (TransactionRepository.lockForUpdate and loanLifecycle). This index only makes that
-- lookup, and the foreign key check, fast.
CREATE INDEX transaction_settles_idx ON transaction (settles_transaction_id);

-- For the balance views (Technical Design 3). Both filter on status = 'approved'.
CREATE INDEX transaction_status_creditor_idx ON transaction (status, creditor_id);
CREATE INDEX transaction_status_debtor_idx   ON transaction (status, debtor_id);

-- ---------------------------------------------------------------------------------
-- transaction_status_history: every transition, retained forever (Data-5).
-- from_status is null for the row that records creation as pending.
-- ---------------------------------------------------------------------------------
CREATE TABLE transaction_status_history (
    history_id     uuid        NOT NULL,
    transaction_id uuid        NOT NULL,
    from_status    text,
    to_status      text        NOT NULL,
    actor_id       uuid        NOT NULL,
    occurred_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT transaction_status_history_pk PRIMARY KEY (history_id),
    CONSTRAINT transaction_status_history_transaction_fk
        FOREIGN KEY (transaction_id) REFERENCES transaction (transaction_id),
    CONSTRAINT transaction_status_history_actor_fk
        FOREIGN KEY (actor_id) REFERENCES member (member_id),
    CONSTRAINT transaction_status_history_from_check
        CHECK (from_status IS NULL OR from_status IN ('pending', 'approved', 'declined', 'cancelled')),
    CONSTRAINT transaction_status_history_to_check
        CHECK (to_status IN ('pending', 'approved', 'declined', 'cancelled'))
);

CREATE INDEX transaction_status_history_transaction_idx
    ON transaction_status_history (transaction_id, occurred_at);

-- ---------------------------------------------------------------------------------
-- notification: the transactional outbox (ADR-010, Technical Design D5 and 7).
-- Written in the same database transaction as the ledger change; sent by a worker
-- after commit. Stores no rendered text: emails are rendered at send time in the
-- recipient's locale (ADR-014).
-- ---------------------------------------------------------------------------------
CREATE TABLE notification (
    notification_id uuid        NOT NULL,
    transaction_id  uuid        NOT NULL,
    recipient_id    uuid        NOT NULL,
    kind            text        NOT NULL,
    state           text        NOT NULL DEFAULT 'pending',
    attempts        integer     NOT NULL DEFAULT 0,
    next_attempt_at timestamptz NOT NULL DEFAULT now(),
    last_error      text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    sent_at         timestamptz,

    CONSTRAINT notification_pk PRIMARY KEY (notification_id),
    CONSTRAINT notification_transaction_fk FOREIGN KEY (transaction_id) REFERENCES transaction (transaction_id),
    CONSTRAINT notification_recipient_fk   FOREIGN KEY (recipient_id)   REFERENCES member (member_id),
    CONSTRAINT notification_kind_check     CHECK (kind IN ('pending_alert', 'settlement_alert')),
    CONSTRAINT notification_state_check    CHECK (state IN ('pending', 'sent', 'failed')),
    CONSTRAINT notification_attempts_check CHECK (attempts >= 0),
    CONSTRAINT notification_sent_at_check  CHECK ((state = 'sent') = (sent_at IS NOT NULL))
);

-- The worker's claim query (Technical Design 7): due rows still pending, oldest first.
CREATE INDEX notification_due_idx ON notification (next_attempt_at) WHERE state = 'pending';

-- ---------------------------------------------------------------------------------
-- Balance views (Technical Design 3). Both sum approved rows only (Dashboard.Net-2).
-- ---------------------------------------------------------------------------------

-- Net position per member and currency (Dashboard.Net-1). Never summed across
-- currencies. Positive means the member is owed; negative means the member owes.
CREATE VIEW member_net AS
SELECT member_id, currency, SUM(delta) AS net_minor
FROM (
    SELECT creditor_id AS member_id, currency,  amount_minor AS delta FROM transaction WHERE status = 'approved'
    UNION ALL
    SELECT debtor_id,               currency, -amount_minor         FROM transaction WHERE status = 'approved'
) e
GROUP BY member_id, currency;

-- Balance within each pair and currency, from the lower member_id's side
-- (Dashboard.Counterparty-*, Auth.Roles-10). Positive: member_b owes member_a.
CREATE VIEW pair_net AS
SELECT LEAST(creditor_id, debtor_id)    AS member_a,
       GREATEST(creditor_id, debtor_id) AS member_b,
       currency,
       SUM(CASE WHEN creditor_id < debtor_id THEN amount_minor ELSE -amount_minor END) AS a_net_minor
FROM transaction
WHERE status = 'approved'
GROUP BY 1, 2, 3;
